class Profile
  include DataMapper::Resource
  property :p_id, Serial
  property :p_cc, Serial
  property :p_degree, Serial
  property :p_twitter_id, Serial
  property :p_screen_name, String
  property :p_realname, String
  property :p_type, Serial
  property :p_location, Text
  property :p_description, Text
  property :p_url, Text
  property :p_language, String
  property :p_website_type, String
  property :p_notes, Text
  property :p_followers, Text
  property :p_following, Text
  property :p_following_count, Serial
  property :p_follower_count, Serial
  property :p_in, Text
  property :p_out, Text
  property :p_statuses_count, Serial
  property :p_picture, Text
  property :p_created_at, DateTime
  property :p_time_zone, String
  property :p_utc_offset, String
  property :p_verified, String
  property :p_geo_enabled, Serial
  property :p_lang, String
  property :p_first_pubdate, DateTime
  property :p_first_text, Text
  property :p_participation, Serial
  property :p_protected, Serial
  property :last_update, DateTime
  property :times, Serial
  property :erhardt, Serial
  property :gilad, Serial
  property :danah, Serial
  property :mike, Serial
  property :p_edited_by, Text
end
